logging:
  level:
    org.springframework.security: DEBUG
security:
  user:
    role: USER,ADMIN
server:
  port: 8082
spring:
    redis:
        host: localhost
        password: qwe123
        port: 6379
